// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google"; // หรือฟอนต์อื่นที่คุณเลือก
import "./globals.css";
import Sidebar from "./components/Sidebar"; // import ตัวที่เราเพิ่งสร้าง

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MiniPro Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50`}>
        <div className="flex min-h-screen">
          {/* ส่วน Sidebar */}
          <Sidebar />

          {/* ส่วนเนื้อหา (Content) จะถูกดันไปทางขวา */}
          <main className="flex-1 ml-64 p-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}